# -*- coding: utf-8 -*-
"""JointGAT_GCN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17tIXzZXfzAPPYnMwrrJDk4eqnKEYAuF2
"""

!pip install torch-geometric

import torch
import torch.nn as nn
import torch.nn.functional as F
import pickle

from torch_geometric.nn import GATConv, GCNConv, global_mean_pool

# protein_graphs.pkl = list of PyG Data objects (your protein graphs)
# protein_graphs = pickle.load(open("/content/ZproteinGraph_split_part_1.pkl", "rb"))
protein_graphs = torch.load("/content/ZproteinGraph_split_part_1.pkl", weights_only=False)

# PPI edges CSV
ppi_edges = []
with open("/content/positive_edge_1024.csv") as f:
    next(f)
    for line in f:
        a, b = line.strip().split(",")
        ppi_edges.append((a, b))

protein_ids = [g.name.split(".")[0] for g in protein_graphs]
id2idx = {p: i for i, p in enumerate(protein_ids)}

edges = []
for a, b in ppi_edges:
    if a in id2idx and b in id2idx:
        i, j = id2idx[a], id2idx[b]
        edges.append([i, j])
        edges.append([j, i])

edge_index = torch.tensor(edges, dtype=torch.long).t().contiguous()

from torch_geometric.nn import SAGPooling

class GAT1(nn.Module):
    def __init__(self, input_dim=24, hidden_dim=512, heads=1):
        super().__init__()

        self.fc1 = nn.Linear(input_dim, hidden_dim)

        self.conv1 = GATConv(hidden_dim, hidden_dim, heads=heads, edge_dim=1)
        self.conv2 = GATConv(hidden_dim, hidden_dim, heads=heads, edge_dim=1)
        self.conv3 = GATConv(hidden_dim, hidden_dim, heads=heads, edge_dim=1)

        self.pool1 = SAGPooling(hidden_dim)
        self.pool2 = SAGPooling(hidden_dim)
        self.pool3 = SAGPooling(hidden_dim)

        self.bn1 = nn.BatchNorm1d(hidden_dim)
        self.bn2 = nn.BatchNorm1d(hidden_dim)
        self.bn3 = nn.BatchNorm1d(hidden_dim)

    def forward(self, data):
        x, edge_index, edge_attr, batch = (
            data.x,
            data.edge_index,
            data.edge_attr,
            data.batch # remove batch
        )

        x = self.fc1(x)

        x_res = x
        x = self.conv1(x, edge_index, edge_attr=edge_attr)
        x = self.bn1(x)
        x = F.relu(x + x_res)
        x, edge_index, edge_attr, batch, _, _ = self.pool1(x, edge_index, edge_attr=edge_attr, batch=batch)

        x_res = x
        x = self.conv2(x, edge_index, edge_attr=edge_attr)
        x = self.bn2(x)
        x = F.relu(x + x_res)
        x, edge_index, edge_attr, batch, _, _ = self.pool2(x, edge_index, edge_attr=edge_attr, batch=batch)

        x_res = x
        x = self.conv3(x, edge_index, edge_attr=edge_attr)
        x = self.bn3(x)
        x = F.relu(x + x_res)
        x, edge_index, edge_attr, batch, _, _ = self.pool3(x, edge_index, edge_attr=edge_attr, batch=batch)

        protein_embedding = global_mean_pool(x, batch)

        return protein_embedding  # [1,512]

class JointGAT_GCN(nn.Module):
    def __init__(self):
        super().__init__()

        self.gat = GAT1()

        # Projection 512 → 64
        self.project = nn.Linear(512, 64)

        # PPI GCN
        self.gcn1 = GCNConv(64, 64)
        self.gcn2 = GCNConv(64, 64)

    def forward(self, protein_graphs, edge_index):
        device = edge_index.device

        embeddings = []

        # ---- GAT FOR EACH PROTEIN ----
        for g in protein_graphs:
            g = g.to(device)              # ✅ MOVE DATA TO GPU
            emb = self.gat(g)              # [1,512]
            emb = self.project(emb)       # [1,64]
            embeddings.append(emb)

        X = torch.cat(embeddings, dim=0)  # [N,64] #tensor may be make to this matrix

        # ---- PPI GCN ----
        X = F.relu(self.gcn1(X, edge_index))
        X = self.gcn2(X, edge_index)

        return X   # final embeddings [N,64]

def link_prediction_loss(z, edge_index): # remove negative edges

    pos_edge = edge_index

    num_nodes = z.size(0)

    # Negative edges
    neg_edge = torch.randint(0, num_nodes, pos_edge.size(), device=z.device)

    # Scores
    pos_score = (z[pos_edge[0]] * z[pos_edge[1]]).sum(dim=1)
    neg_score = (z[neg_edge[0]] * z[neg_edge[1]]).sum(dim=1)

    # Labels
    pos_label = torch.ones_like(pos_score)
    neg_label = torch.zeros_like(neg_score)

    loss = F.binary_cross_entropy_with_logits(pos_score, pos_label) + \
           F.binary_cross_entropy_with_logits(neg_score, neg_label)

    return loss

def forward(self, protein_graphs, edge_index):

    device = edge_index.device   # 👈 get device

    embeddings = []

    for g in protein_graphs:
        g = g.to(device)         # ✅ MOVE DATA TO GPU
        emb = self.gat(g)
        emb = self.project(emb)
        embeddings.append(emb)

    X = torch.cat(embeddings, dim=0)

    X = F.relu(self.gcn1(X, edge_index))
    X = self.gcn2(X, edge_index)

    return X

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = JointGAT_GCN().to(device)
edge_index = edge_index.to(device)

optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

for epoch in range(15):

    model.train()
    optimizer.zero_grad()

    z = model(protein_graphs, edge_index)   # [N,64]

    loss = link_prediction_loss(z, edge_index)

    loss.backward()
    optimizer.step()

    print(f"Epoch {epoch+1}, Loss: {loss.item():.4f}")

model.eval()

with torch.no_grad():
    final_embeddings = model(protein_graphs, edge_index)

# Save embeddings
emb_dict = {}
for i, p in enumerate(protein_ids):
    emb_dict[p] = final_embeddings[i].cpu().numpy()

pickle.dump(emb_dict, open("ppi_embeddings_64.pkl", "wb"))

# Save models separately
torch.save(model.gat.state_dict(), "GAT1_trained.pt")
torch.save(model.state_dict(), "Joint_GAT_GCN.pt")

print("Saved everything ✅")

