# -*- coding: utf-8 -*-
"""ComplexPredictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YCI5TGCjOzvwq8JVAy7coqYliSDzgvvz
"""

!pip install torch-geometric

import pickle
import json
import torch
import random
from torch_geometric.data import Data

# Load embeddings
with open("protein_embeddings_64.pkl", "rb") as f:
    embeddings = pickle.load(f)

# Load complexes
with open("protein_complexes.json", "r") as f:
    complexes = json.load(f)

# Load PPI edges
ppi_edges = []
with open("ppi_edges.csv", "r") as f:
    next(f)
    for line in f:
        a, b = line.strip().split(",")
        ppi_edges.append((a, b))

# Build lookup
ppi_set = set(ppi_edges) | set([(b,a) for a,b in ppi_edges])

def build_subgraph(proteins):
    node_map = {p:i for i,p in enumerate(proteins)}
    edges = []

    for i in range(len(proteins)):
        for j in range(len(proteins)):
            if i != j:
                if (proteins[i], proteins[j]) in ppi_set:
                    edges.append([node_map[proteins[i]], node_map[proteins[j]]])

    # If no edges → add self loops (important)
    if len(edges) == 0:
        edges = [[0,0],[1,1],[2,2]]

    edge_index = torch.tensor(edges, dtype=torch.long).t().contiguous()
    return edge_index

dataset = []

# Positive samples
for comp in complexes:
    try:
        x = torch.tensor([embeddings[p] for p in comp], dtype=torch.float)
        edge_index = build_subgraph(comp)

        dataset.append(Data(x=x, edge_index=edge_index, y=torch.tensor([1.0])))
    except:
        continue

# Negative samples
proteins = list(embeddings.keys())

for _ in range(len(dataset)):
    p = random.sample(proteins, 3)

    try:
        x = torch.tensor([embeddings[i] for i in p], dtype=torch.float)
        edge_index = build_subgraph(p)

        dataset.append(Data(x=x, edge_index=edge_index, y=torch.tensor([0.0])))
    except:
        continue

import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn import GCNConv, global_mean_pool, global_max_pool

class ComplexPredictor(nn.Module):
    def __init__(self, in_dim=64, hidden=128):
        super().__init__()

        self.conv1 = GCNConv(in_dim, hidden)
        self.conv2 = GCNConv(hidden, hidden)
        self.conv3 = GCNConv(hidden, hidden)

        self.bn1 = nn.BatchNorm1d(hidden)
        self.bn2 = nn.BatchNorm1d(hidden)
        self.bn3 = nn.BatchNorm1d(hidden)

        # Interaction layer
        self.interaction = nn.Linear(hidden * 3, hidden)

        # Final layers
        self.fc1 = nn.Linear(hidden * 2, hidden)
        self.fc2 = nn.Linear(hidden, 1)

    def forward(self, x, edge_index, batch):

        x = F.relu(self.bn1(self.conv1(x, edge_index)))
        x = F.relu(self.bn2(self.conv2(x, edge_index)))
        x = F.relu(self.bn3(self.conv3(x, edge_index)))

        # Pooling
        mean_pool = global_mean_pool(x, batch)
        max_pool = global_max_pool(x, batch)

        # Combine
        pooled = torch.cat([mean_pool, max_pool], dim=1)

        out = F.relu(self.fc1(pooled))
        out = self.fc2(out)

        return out.squeeze()

from torch_geometric.loader import DataLoader

loader = DataLoader(dataset, batch_size=32, shuffle=True)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = ComplexPredictor().to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
criterion = nn.BCEWithLogitsLoss()

for epoch in range(20):
    model.train()
    total_loss = 0

    for batch in loader:
        batch = batch.to(device)

        optimizer.zero_grad()
        out = model(batch.x, batch.edge_index, batch.batch)
        loss = criterion(out, batch.y.view(-1))

        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {total_loss:.4f}")

torch.save(model.state_dict(), "complex_predictor.pt")

model.eval()

def predict_complex(p1, p2, p3):
    proteins = [p1, p2, p3]

    x = torch.tensor([embeddings[p] for p in proteins], dtype=torch.float).to(device)
    edge_index = build_subgraph(proteins).to(device)

    batch = torch.zeros(3, dtype=torch.long).to(device)

    with torch.no_grad():
        logit = model(x, edge_index, batch)
        prob = torch.sigmoid(logit)

    return prob.item()

print(predict_complex("P25054", "P30622", "P46940"))